AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/migrate/schema.rb'
    - 'db/schema.rb'
    - 'node_modules/**/*'

Metrics/AbcSize:
  Max: 25

Style/Documentation:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'
    - 'db/schema.rb'
    - 'config/**/*'

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 250

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 10

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/GuardClause:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false
