default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dorm_development

test:
  <<: *default
  database: dorm_test

production:
  <<: *default
  database: dorm_production
  username: dorm
  password: <%= ENV['DORM_DATABASE_PASSWORD'] %>
