name: Rails - Install dependencies and run linters

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.5

      - name: Build app
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler:1.17.3
          bundle install --jobs 4 --retry 3
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: Run brakeman
        run: |
          bin/brakeman -q -w2
 
      - name: Run bundle-audit
        run: |
          bin/bundle-audit check --update

      - name: Run rubocop
        run: |
          bin/rubocop --parallel