name: Install dependencies, run linters and security checks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.8
          bundler-cache: true 

      - name: Build app
        run: |
          sudo apt-get -yqq install libpq-dev libv8-dev
          gem install bundler:1.17.3
          bundle install --jobs 4 --retry 3

      - name: Run brakeman
        run: |
          bundle exec brakeman -q -w2
 
      - name: Run bundle-audit
        run: |
          bundle exec bundle-audit check --update

      - name: Run rubocop
        run: |
          bundle exec rubocop --parallel
